env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - g++-4.8
      - dbus
      - pulseaudio
      - libpulse-dev
      
language: node_js
node_js: node

install:
  - bash ./startPulse.sh
  - npm install

script:
  - npm test
