dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - pulseaudio
      - libpulse-dev
      
language: node_js
node_js: node

install:
  - npm install

script:
  - npm test
